name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        version: [{go: '1.19.7', golangci: 'v1.52.0'}, {go: '1.20.2', golangci: 'latest'}]
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Setup go ${{ matrix.version.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version.go }}
      - name: Checkout Source
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
         version: ${{ matrix.version.golangci }}
      - name: Run tests
        run: make test
      - name: Run benchmarks
        run: make bench
