name: test

on:
  pull_request:
    branches: ['*']

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.17.x", "1.18.x"]
        include:
        - go: 1.18.x
          latest: true

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load cached dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Download dependencies
        run: go mod download

      - name: Format and lint
        if: matrix.latest
        run: make fmt

      - name: Test
        run: make test
